name: Dev client Depoly
on:
  push:
    branches:
      - dev
    paths:
      - 'client/**'

env:
  working-directory: ./client #root 폴더 설정

jobs:
  client:
    runs-on: ubuntu-latest #배포 실행될 환경
    steps: 
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install -g npm@latest
          npx create-react-app my-app
        working-directory: ./client #디렉토리명

      - name: Install @babel/plugin-proposal-private-property-in-object
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.DEV_AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version

      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.DEV_AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://celebee004 \
            --delete
        working-directory: ./client
